"""Data center static catalog and dictionary definitions."""

TEST_ISOLATION_DATA_ACCOUNT_ID = "test_isolation_account"


def _dictionary_record(
    table_name: str,
    field_name: str,
    field_type: str,
    description: str,
    example_value: str,
    unit: str = "无",
    strategy_usage: str = "不建议策略直接读取，仅用于页面展示或系统追踪。",
    is_indexed: bool = False,
) -> dict[str, object]:
    return {
        "table_name": table_name,
        "field_name": field_name,
        "field_type": field_type,
        "description": description,
        "example_value": example_value,
        "unit": unit,
        "strategy_usage": strategy_usage,
        "is_indexed": is_indexed,
    }


MARKET_STRATEGY_USAGE = "策略可通过 StrategyContext 读取；回测时只能读取当前时间点及以前的数据。"
ACCOUNT_STRATEGY_USAGE = "可作为只读账户/持仓参考；策略只能生成信号，不能据此直接下单。"
TRADE_STRATEGY_USAGE = "不建议作为普通选股字段；主要用于交易一致性、复盘和防重复追踪。"
SIGNAL_STRATEGY_USAGE = "策略输出字段；可进入信号下单流程，但不会自动实盘下单。"
BACKTEST_STRATEGY_USAGE = "回测研究输出字段；用于评估策略，不作为实时策略输入。"
SYSTEM_STRATEGY_USAGE = "系统治理字段；不用于策略逻辑。"


DICTIONARY_RECORDS = [
    _dictionary_record("stock_basic", "symbol", "TEXT", "标准股票代码，格式 600000.SH / 000001.SZ。", "600000.SH", strategy_usage=MARKET_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("stock_basic", "name", "TEXT", "股票名称。", "浦发银行", strategy_usage=MARKET_STRATEGY_USAGE),
    _dictionary_record("stock_basic", "market", "TEXT", "交易市场，常见取值 SH/SZ/BJ。", "SH", strategy_usage=MARKET_STRATEGY_USAGE),
    _dictionary_record("stock_basic", "security_type", "TEXT", "证券类型，例如股票、ETF。", "股票", strategy_usage=MARKET_STRATEGY_USAGE),
    _dictionary_record("stock_basic", "list_status", "TEXT", "上市状态，可用于过滤退市或暂停标的。", "上市", strategy_usage=MARKET_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("stock_basic", "is_st", "INTEGER", "是否 ST，1 表示是，0 表示否。", "0", strategy_usage=MARKET_STRATEGY_USAGE),
    _dictionary_record("stock_basic", "updated_at", "TEXT", "股票基础信息最近更新时间，北京时间。", "2026-05-08 15:00:00", strategy_usage=MARKET_STRATEGY_USAGE),

    _dictionary_record("instrument_detail", "symbol", "TEXT", "标准股票代码。", "600000.SH", strategy_usage=MARKET_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("instrument_detail", "exchange_id", "TEXT", "交易所或市场代码。", "SH", strategy_usage=MARKET_STRATEGY_USAGE),
    _dictionary_record("instrument_detail", "instrument_id", "TEXT", "合约代码。", "600000", strategy_usage=MARKET_STRATEGY_USAGE),
    _dictionary_record("instrument_detail", "instrument_name", "TEXT", "合约名称。", "浦发银行", strategy_usage=MARKET_STRATEGY_USAGE),
    _dictionary_record("instrument_detail", "exchange_code", "TEXT", "交易所返回代码。", "SH", strategy_usage=MARKET_STRATEGY_USAGE),
    _dictionary_record("instrument_detail", "open_date", "TEXT", "上市日期。", "1999-11-10", strategy_usage=MARKET_STRATEGY_USAGE),
    _dictionary_record("instrument_detail", "expire_date", "TEXT", "退市日或到期日，普通股票通常为空。", "", strategy_usage=MARKET_STRATEGY_USAGE),
    _dictionary_record("instrument_detail", "pre_close", "REAL", "前收价。", "9.12", "元", MARKET_STRATEGY_USAGE),
    _dictionary_record("instrument_detail", "up_stop_price", "REAL", "当日涨停价，来自官方合约详情可用字段。", "10.03", "元", MARKET_STRATEGY_USAGE),
    _dictionary_record("instrument_detail", "down_stop_price", "REAL", "当日跌停价，来自官方合约详情可用字段。", "8.21", "元", MARKET_STRATEGY_USAGE),
    _dictionary_record("instrument_detail", "is_trading", "INTEGER", "是否可交易，1 表示可交易。", "1", strategy_usage=MARKET_STRATEGY_USAGE),
    _dictionary_record("instrument_detail", "instrument_status", "TEXT", "合约状态。", "正常", strategy_usage=MARKET_STRATEGY_USAGE),
    _dictionary_record("instrument_detail", "total_volume", "REAL", "总股本或合约总量，如官方字段可用则保存。", "29352080000", "股", MARKET_STRATEGY_USAGE),
    _dictionary_record("instrument_detail", "float_volume", "REAL", "流通股本或流通量，如官方字段可用则保存。", "29352080000", "股", MARKET_STRATEGY_USAGE),
    _dictionary_record("instrument_detail", "trading_day", "TEXT", "合约详情对应交易日。", "2026-05-08", strategy_usage=MARKET_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("instrument_detail", "raw_json", "TEXT", "官方原始返回 JSON，便于后续扩展字段。", "{\"source\":\"qmt\",\"raw\":true}", strategy_usage=SYSTEM_STRATEGY_USAGE),
    _dictionary_record("instrument_detail", "sync_time", "TEXT", "合约详情同步时间。", "2026-05-10 13:30:00", strategy_usage=SYSTEM_STRATEGY_USAGE, is_indexed=True),

    _dictionary_record("trading_calendar", "market", "TEXT", "市场代码，SH / SZ / BJ。", "SH", strategy_usage=MARKET_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("trading_calendar", "trade_date", "TEXT", "交易日期，格式 YYYY-MM-DD。", "2026-05-08", strategy_usage=MARKET_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("trading_calendar", "is_trading_day", "INTEGER", "是否交易日，1 表示交易日。", "1", strategy_usage=MARKET_STRATEGY_USAGE),
    _dictionary_record("trading_calendar", "source", "TEXT", "交易日历来源。", "qmt", strategy_usage=SYSTEM_STRATEGY_USAGE),
    _dictionary_record("trading_calendar", "sync_time", "TEXT", "交易日历同步时间。", "2026-05-10 13:30:00", strategy_usage=SYSTEM_STRATEGY_USAGE),

    _dictionary_record("daily_kline", "symbol", "TEXT", "标准股票代码。", "600000.SH", strategy_usage=MARKET_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("daily_kline", "trade_date", "TEXT", "交易日期，格式 YYYY-MM-DD，北京时间。", "2026-05-08", strategy_usage=MARKET_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("daily_kline", "open", "REAL", "日 K 开盘价。", "9.10", "元", MARKET_STRATEGY_USAGE),
    _dictionary_record("daily_kline", "high", "REAL", "日 K 最高价。", "9.28", "元", MARKET_STRATEGY_USAGE),
    _dictionary_record("daily_kline", "low", "REAL", "日 K 最低价。", "9.02", "元", MARKET_STRATEGY_USAGE),
    _dictionary_record("daily_kline", "close", "REAL", "日 K 收盘价。", "9.12", "元", MARKET_STRATEGY_USAGE),
    _dictionary_record("daily_kline", "pre_close", "REAL", "前收价；停牌补齐行用于估值参考。", "9.08", "元", MARKET_STRATEGY_USAGE),
    _dictionary_record("daily_kline", "volume", "REAL", "日 K 成交量。", "1000000", "股", MARKET_STRATEGY_USAGE),
    _dictionary_record("daily_kline", "amount", "REAL", "日 K 成交额。", "9000000", "元", MARKET_STRATEGY_USAGE),
    _dictionary_record("daily_kline", "suspend_flag", "INTEGER", "QMT 停牌标记；1 表示该交易日不可成交。", "0", strategy_usage=MARKET_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("daily_kline", "created_at", "TEXT", "本地落库时间。", "2026-05-08 15:01:00", strategy_usage=SYSTEM_STRATEGY_USAGE),

    _dictionary_record("minute_kline", "symbol", "TEXT", "标准股票代码。", "600000.SH", strategy_usage=MARKET_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("minute_kline", "datetime", "TEXT", "分钟 K 时间，格式 YYYY-MM-DD HH:mm:ss，北京时间。", "2026-05-08 09:31:00", strategy_usage=MARKET_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("minute_kline", "period", "TEXT", "分钟周期，第一版支持 1m/5m。", "1m", strategy_usage=MARKET_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("minute_kline", "open", "REAL", "分钟 K 开盘价。", "9.10", "元", MARKET_STRATEGY_USAGE),
    _dictionary_record("minute_kline", "high", "REAL", "分钟 K 最高价。", "9.16", "元", MARKET_STRATEGY_USAGE),
    _dictionary_record("minute_kline", "low", "REAL", "分钟 K 最低价。", "9.09", "元", MARKET_STRATEGY_USAGE),
    _dictionary_record("minute_kline", "close", "REAL", "分钟 K 收盘价。", "9.12", "元", MARKET_STRATEGY_USAGE),
    _dictionary_record("minute_kline", "pre_close", "REAL", "前收价；分钟 K 未返回时为 0。", "9.08", "元", MARKET_STRATEGY_USAGE),
    _dictionary_record("minute_kline", "volume", "REAL", "分钟 K 成交量。", "10000", "股", MARKET_STRATEGY_USAGE),
    _dictionary_record("minute_kline", "amount", "REAL", "分钟 K 成交额。", "91200", "元", MARKET_STRATEGY_USAGE),
    _dictionary_record("minute_kline", "suspend_flag", "INTEGER", "QMT 停牌标记；分钟 K 通常为 0。", "0", strategy_usage=MARKET_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("minute_kline", "created_at", "TEXT", "本地落库时间。", "2026-05-08 09:32:00", strategy_usage=SYSTEM_STRATEGY_USAGE),

    _dictionary_record("account_snapshot", "account_id", "TEXT", "账户 ID。", "demo_account", strategy_usage=ACCOUNT_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("account_snapshot", "total_asset", "REAL", "账户总资产。", "1086500.25", "元", ACCOUNT_STRATEGY_USAGE),
    _dictionary_record("account_snapshot", "available_cash", "REAL", "账户可用资金。", "520000.00", "元", ACCOUNT_STRATEGY_USAGE),
    _dictionary_record("account_snapshot", "frozen_cash", "REAL", "账户冻结资金。", "0.00", "元", ACCOUNT_STRATEGY_USAGE),
    _dictionary_record("account_snapshot", "market_value", "REAL", "持仓市值。", "566500.25", "元", ACCOUNT_STRATEGY_USAGE),
    _dictionary_record("account_snapshot", "today_pnl", "REAL", "今日盈亏。", "-572.02", "元", ACCOUNT_STRATEGY_USAGE),
    _dictionary_record("account_snapshot", "snapshot_time", "TEXT", "账户快照时间，北京时间。", "2026-05-10 09:12:05", strategy_usage=ACCOUNT_STRATEGY_USAGE, is_indexed=True),

    _dictionary_record("position_snapshot", "account_id", "TEXT", "账户 ID。", "demo_account", strategy_usage=ACCOUNT_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("position_snapshot", "symbol", "TEXT", "标准股票代码。", "600000.SH", strategy_usage=ACCOUNT_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("position_snapshot", "name", "TEXT", "股票名称。", "浦发银行", strategy_usage=ACCOUNT_STRATEGY_USAGE),
    _dictionary_record("position_snapshot", "quantity", "INTEGER", "持仓数量。", "1000", "股", ACCOUNT_STRATEGY_USAGE),
    _dictionary_record("position_snapshot", "available_quantity", "INTEGER", "可卖数量，受 T+1 等规则影响。", "800", "股", ACCOUNT_STRATEGY_USAGE),
    _dictionary_record("position_snapshot", "cost_price", "REAL", "持仓成本价。", "9.10", "元", ACCOUNT_STRATEGY_USAGE),
    _dictionary_record("position_snapshot", "last_price", "REAL", "最新价。", "9.25", "元", ACCOUNT_STRATEGY_USAGE),
    _dictionary_record("position_snapshot", "market_value", "REAL", "持仓市值。", "9250.00", "元", ACCOUNT_STRATEGY_USAGE),
    _dictionary_record("position_snapshot", "pnl", "REAL", "持仓浮动盈亏。", "150.00", "元", ACCOUNT_STRATEGY_USAGE),
    _dictionary_record("position_snapshot", "pnl_ratio", "REAL", "持仓盈亏比例。", "1.64", "%", ACCOUNT_STRATEGY_USAGE),
    _dictionary_record("position_snapshot", "snapshot_time", "TEXT", "持仓快照时间，北京时间。", "2026-05-10 09:12:05", strategy_usage=ACCOUNT_STRATEGY_USAGE, is_indexed=True),

    _dictionary_record("order_record", "local_order_id", "TEXT", "本地订单 ID，调用 QMT 前生成。", "order_20260510_001", strategy_usage=TRADE_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("order_record", "qmt_order_id", "TEXT", "QMT 返回的委托编号。", "qmt_123456", strategy_usage=TRADE_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("order_record", "account_id", "TEXT", "账户 ID。", "demo_account", strategy_usage=TRADE_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("order_record", "symbol", "TEXT", "标准股票代码。", "600000.SH", strategy_usage=TRADE_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("order_record", "name", "TEXT", "股票名称。", "浦发银行", strategy_usage=TRADE_STRATEGY_USAGE),
    _dictionary_record("order_record", "side", "TEXT", "买卖方向，BUY/SELL。", "BUY", strategy_usage=TRADE_STRATEGY_USAGE),
    _dictionary_record("order_record", "price", "REAL", "委托价格。", "9.12", "元", TRADE_STRATEGY_USAGE),
    _dictionary_record("order_record", "quantity", "INTEGER", "委托数量。", "100", "股", TRADE_STRATEGY_USAGE),
    _dictionary_record("order_record", "filled_quantity", "INTEGER", "已成交数量。", "100", "股", TRADE_STRATEGY_USAGE),
    _dictionary_record("order_record", "status", "TEXT", "内部订单状态。", "全部成交", strategy_usage=TRADE_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("order_record", "qmt_status", "TEXT", "QMT 原始或映射状态。", "已成", strategy_usage=TRADE_STRATEGY_USAGE),
    _dictionary_record("order_record", "source", "TEXT", "订单来源，manual/signal/auto/real_sync/test_sync；test_sync 仅用于测试隔离，不作为默认业务数据。", "signal", strategy_usage=TRADE_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("order_record", "strategy_id", "TEXT", "策略 ID 或策略名称关联。", "1", strategy_usage=TRADE_STRATEGY_USAGE),
    _dictionary_record("order_record", "signal_id", "TEXT", "策略信号 ID。", "25", strategy_usage=TRADE_STRATEGY_USAGE),
    _dictionary_record("order_record", "idempotency_key", "TEXT", "防重复下单幂等键。", "signal:25", strategy_usage=TRADE_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("order_record", "order_time", "TEXT", "委托创建时间，北京时间。", "2026-05-10 10:00:00", strategy_usage=TRADE_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("order_record", "updated_at", "TEXT", "订单状态更新时间，北京时间。", "2026-05-10 10:00:05", strategy_usage=TRADE_STRATEGY_USAGE),

    _dictionary_record("trade_record", "trade_id", "TEXT", "成交 ID，防重复写入主键。", "trade_20260510_001", strategy_usage=TRADE_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("trade_record", "local_order_id", "TEXT", "关联本地订单 ID。", "order_20260510_001", strategy_usage=TRADE_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("trade_record", "qmt_order_id", "TEXT", "关联 QMT 委托编号。", "qmt_123456", strategy_usage=TRADE_STRATEGY_USAGE),
    _dictionary_record("trade_record", "account_id", "TEXT", "账户 ID。", "demo_account", strategy_usage=TRADE_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("trade_record", "symbol", "TEXT", "标准股票代码。", "600000.SH", strategy_usage=TRADE_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("trade_record", "name", "TEXT", "股票名称。", "浦发银行", strategy_usage=TRADE_STRATEGY_USAGE),
    _dictionary_record("trade_record", "side", "TEXT", "成交方向，BUY/SELL。", "BUY", strategy_usage=TRADE_STRATEGY_USAGE),
    _dictionary_record("trade_record", "price", "REAL", "成交价格。", "9.12", "元", TRADE_STRATEGY_USAGE),
    _dictionary_record("trade_record", "quantity", "INTEGER", "成交数量。", "100", "股", TRADE_STRATEGY_USAGE),
    _dictionary_record("trade_record", "amount", "REAL", "成交金额。", "912.00", "元", TRADE_STRATEGY_USAGE),
    _dictionary_record("trade_record", "fee", "REAL", "手续费。", "1.00", "元", TRADE_STRATEGY_USAGE),
    _dictionary_record("trade_record", "source", "TEXT", "成交来源，manual/signal/real_sync/test_sync；test_sync 仅用于测试隔离，不作为默认业务数据。", "signal", strategy_usage=TRADE_STRATEGY_USAGE),
    _dictionary_record("trade_record", "trade_time", "TEXT", "成交时间，北京时间。", "2026-05-10 10:00:03", strategy_usage=TRADE_STRATEGY_USAGE, is_indexed=True),

    _dictionary_record("strategy_signal", "strategy_id", "INTEGER", "生成信号的策略 ID。", "1", strategy_usage=SIGNAL_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("strategy_signal", "run_id", "TEXT", "策略运行批次 ID。", "run_20260510_001", strategy_usage=SIGNAL_STRATEGY_USAGE),
    _dictionary_record("strategy_signal", "symbol", "TEXT", "标准股票代码。", "600000.SH", strategy_usage=SIGNAL_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("strategy_signal", "name", "TEXT", "股票名称。", "浦发银行", strategy_usage=SIGNAL_STRATEGY_USAGE),
    _dictionary_record("strategy_signal", "action", "TEXT", "信号方向，BUY/SELL/HOLD。", "BUY", strategy_usage=SIGNAL_STRATEGY_USAGE),
    _dictionary_record("strategy_signal", "price", "REAL", "信号参考价格。", "9.12", "元", SIGNAL_STRATEGY_USAGE),
    _dictionary_record("strategy_signal", "amount", "REAL", "信号建议金额。", "100000", "元", SIGNAL_STRATEGY_USAGE),
    _dictionary_record("strategy_signal", "reason", "TEXT", "触发原因。", "均线放量触发", strategy_usage=SIGNAL_STRATEGY_USAGE),
    _dictionary_record("strategy_signal", "status", "TEXT", "信号状态，未处理/已下单/已忽略等。", "未处理", strategy_usage=SIGNAL_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("strategy_signal", "signal_time", "TEXT", "信号时间，北京时间。", "2026-05-10 10:15:00", strategy_usage=SIGNAL_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("strategy_signal", "order_id", "TEXT", "关联本地订单 ID。", "order_20260510_001", strategy_usage=SIGNAL_STRATEGY_USAGE),
    _dictionary_record("strategy_signal", "created_at", "TEXT", "信号落库时间。", "2026-05-10 10:15:01", strategy_usage=SIGNAL_STRATEGY_USAGE),

    _dictionary_record("backtest_task", "task_id", "TEXT", "回测任务 ID。", "task_backtest_001", strategy_usage=BACKTEST_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("backtest_task", "backtest_name", "TEXT", "回测名称。", "均线策略回测", strategy_usage=BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_task", "strategy_id", "INTEGER", "回测使用的策略 ID。", "1", strategy_usage=BACKTEST_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("backtest_task", "start_date", "TEXT", "回测开始日期。", "2026-01-01", strategy_usage=BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_task", "end_date", "TEXT", "回测结束日期。", "2026-05-08", strategy_usage=BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_task", "initial_cash", "REAL", "初始资金。", "1000000", "元", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_task", "single_order_amount", "REAL", "单笔下单金额。", "100000", "元", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_task", "data_frequency", "TEXT", "回测数据周期。", "daily", strategy_usage=BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_task", "fill_mode", "TEXT", "成交撮合模式。", "next_bar", strategy_usage=BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_task", "fee_rate", "REAL", "手续费率。", "0.0003", "比例", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_task", "stamp_tax_rate", "REAL", "印花税率。", "0.001", "比例", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_task", "slippage", "REAL", "滑点。", "0.01", "元", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_task", "status", "TEXT", "回测任务状态。", "success", strategy_usage=BACKTEST_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("backtest_task", "created_at", "TEXT", "回测任务创建时间。", "2026-05-10 11:00:00", strategy_usage=BACKTEST_STRATEGY_USAGE),

    _dictionary_record("backtest_result", "backtest_id", "INTEGER", "关联回测任务内部 ID。", "1", strategy_usage=BACKTEST_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("backtest_result", "total_return", "REAL", "总收益率。", "0.125", "比例", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_result", "annual_return", "REAL", "年化收益率。", "0.18", "比例", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_result", "max_drawdown", "REAL", "最大回撤。", "0.08", "比例", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_result", "win_rate", "REAL", "胜率。", "0.55", "比例", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_result", "trade_count", "INTEGER", "交易次数。", "12", "次", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_result", "profit_loss_ratio", "REAL", "盈亏比。", "1.8", "倍", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_result", "average_holding_days", "REAL", "平均持仓天数。", "6.5", "天", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_result", "final_cash", "REAL", "期末资金。", "1125000", "元", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_result", "created_at", "TEXT", "结果生成时间。", "2026-05-10 11:05:00", strategy_usage=BACKTEST_STRATEGY_USAGE),

    _dictionary_record("backtest_trade", "backtest_id", "INTEGER", "关联回测任务内部 ID。", "1", strategy_usage=BACKTEST_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("backtest_trade", "symbol", "TEXT", "标准股票代码。", "600000.SH", strategy_usage=BACKTEST_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("backtest_trade", "name", "TEXT", "股票名称。", "浦发银行", strategy_usage=BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_trade", "side", "TEXT", "回测交易方向，BUY/SELL。", "BUY", strategy_usage=BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_trade", "price", "REAL", "回测成交价格。", "9.12", "元", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_trade", "quantity", "INTEGER", "回测成交数量。", "100", "股", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_trade", "amount", "REAL", "回测成交金额。", "912.00", "元", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_trade", "fee", "REAL", "回测手续费。", "1.00", "元", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_trade", "trade_time", "TEXT", "回测成交时间。", "2026-05-08 09:35:00", strategy_usage=BACKTEST_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("backtest_trade", "reason", "TEXT", "回测成交原因。", "信号延迟成交", strategy_usage=BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_trade", "pnl", "REAL", "该笔回测交易盈亏。", "120.00", "元", BACKTEST_STRATEGY_USAGE),

    _dictionary_record("backtest_equity", "backtest_id", "INTEGER", "关联回测任务内部 ID。", "1", strategy_usage=BACKTEST_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("backtest_equity", "trade_date", "TEXT", "权益曲线日期。", "2026-05-08", strategy_usage=BACKTEST_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("backtest_equity", "equity", "REAL", "账户权益。", "1012000", "元", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_equity", "cash", "REAL", "现金余额。", "800000", "元", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_equity", "market_value", "REAL", "持仓市值。", "212000", "元", BACKTEST_STRATEGY_USAGE),
    _dictionary_record("backtest_equity", "drawdown", "REAL", "当前回撤。", "0.03", "比例", BACKTEST_STRATEGY_USAGE),

    _dictionary_record("data_coverage", "data_type", "TEXT", "覆盖率检查的数据类型。", "daily_kline", strategy_usage=SYSTEM_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("data_coverage", "symbol", "TEXT", "覆盖范围，ALL 表示汇总范围。", "ALL", strategy_usage=SYSTEM_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("data_coverage", "period", "TEXT", "数据周期，例如 1d / 1m。", "1d", strategy_usage=SYSTEM_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("data_coverage", "start_date", "TEXT", "覆盖率检查开始日期。", "2026-01-01", strategy_usage=SYSTEM_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("data_coverage", "end_date", "TEXT", "覆盖率检查结束日期。", "2026-05-08", strategy_usage=SYSTEM_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("data_coverage", "expected_trading_days", "INTEGER", "预期交易日数量；当前批次按工作日粗算。", "85", "天", SYSTEM_STRATEGY_USAGE),
    _dictionary_record("data_coverage", "actual_trading_days", "INTEGER", "本地库实际有数据的交易日数量。", "80", "天", SYSTEM_STRATEGY_USAGE),
    _dictionary_record("data_coverage", "expected_rows", "INTEGER", "预期覆盖单位数；日K为股票-交易日行数，分钟K汇总为股票-交易日覆盖单位，不等于分钟原始bar数。", "5000", "覆盖单位", SYSTEM_STRATEGY_USAGE),
    _dictionary_record("data_coverage", "actual_rows", "INTEGER", "实际覆盖单位数；日K为落库K线行数，分钟K汇总为已覆盖股票-交易日数量。分钟原始bar数请看同步任务写入行数或K线表。", "4800", "覆盖单位", SYSTEM_STRATEGY_USAGE),
    _dictionary_record("data_coverage", "missing_days", "TEXT", "缺失日期 JSON 数组，最多展示前若干项。", "[\"2026-02-18\"]", strategy_usage=SYSTEM_STRATEGY_USAGE),
    _dictionary_record("data_coverage", "duplicate_rows", "INTEGER", "重复唯一键分组数量。", "0", "组", SYSTEM_STRATEGY_USAGE),
    _dictionary_record("data_coverage", "coverage_rate", "REAL", "覆盖率百分比。", "96.00", "%", SYSTEM_STRATEGY_USAGE),
    _dictionary_record("data_coverage", "status", "TEXT", "覆盖状态：complete/partial/missing/failed。", "partial", strategy_usage=SYSTEM_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("data_coverage", "checked_at", "TEXT", "覆盖率检查时间。", "2026-05-10 13:20:00", strategy_usage=SYSTEM_STRATEGY_USAGE, is_indexed=True),

    _dictionary_record("sync_cursor", "source_code", "TEXT", "数据源编码。", "qmt", strategy_usage=SYSTEM_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("sync_cursor", "data_type", "TEXT", "同步数据类型。", "daily_kline", strategy_usage=SYSTEM_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("sync_cursor", "symbol", "TEXT", "同步游标对应股票；全局数据可为空字符串。", "600000.SH", strategy_usage=SYSTEM_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("sync_cursor", "period", "TEXT", "分钟 K 周期；非分钟数据可为空字符串。", "1m", strategy_usage=SYSTEM_STRATEGY_USAGE, is_indexed=True),
    _dictionary_record("sync_cursor", "last_sync_time", "TEXT", "最后同步到的时间或日期。", "2026-05-08 15:00:00", strategy_usage=SYSTEM_STRATEGY_USAGE),
    _dictionary_record("sync_cursor", "updated_at", "TEXT", "同步游标更新时间。", "2026-05-08 15:01:00", strategy_usage=SYSTEM_STRATEGY_USAGE),
]

QUALITY_EXPECTED_MIN_CHECKS = 24

OFFICIAL_UNSUPPORTED_ITEMS = [
    "Level2 行情：l2quote / l2order / l2transaction / l2orderqueue",
    "信用账户与融资融券：query_credit_detail / query_stk_compacts 等",
    "期货、期权、港股通专项、投研版特色与 VIP 专属数据",
    "全市场 Tick 2026 全年默认落库",
    "Tushare、聚宽、米筐、Wind、AkShare 等外部数据源",
]

OFFICIAL_CATALOG_ITEMS = [
    {
        "data_type": "account_snapshot",
        "name": "账户资产",
        "category": "账户数据",
        "source_module": "xttrader",
        "official_interface": "query_stock_asset(account)",
        "local_table": "account_snapshot",
        "enabled": True,
        "required_for_backtest": False,
        "priority": "P0",
        "account_boundary": "普通股票账户可用",
        "sync_frequency": "盘前、盘中、盘后",
        "notes": "只读查询，总览和交易执行页面使用；不触发真实下单。",
    },
    {
        "data_type": "position_snapshot",
        "name": "当前持仓",
        "category": "账户数据",
        "source_module": "xttrader",
        "official_interface": "query_stock_positions(account)",
        "local_table": "position_snapshot",
        "enabled": True,
        "required_for_backtest": False,
        "priority": "P0",
        "account_boundary": "普通股票账户可用",
        "sync_frequency": "盘前、盘中、盘后",
        "notes": "用于持仓展示和策略只读参考，策略仍只能生成信号。",
    },
    {
        "data_type": "order_record",
        "name": "当日委托",
        "category": "账户数据",
        "source_module": "xttrader",
        "official_interface": "query_stock_orders(account, cancelable_only=False)",
        "local_table": "order_record",
        "enabled": True,
        "required_for_backtest": False,
        "priority": "P0",
        "account_boundary": "普通股票账户可用",
        "sync_frequency": "盘中 3-5 秒、盘后补齐",
        "notes": "普通查询通常只返回当日委托，必须每日落库。",
    },
    {
        "data_type": "trade_record",
        "name": "当日成交",
        "category": "账户数据",
        "source_module": "xttrader",
        "official_interface": "query_stock_trades(account)",
        "local_table": "trade_record",
        "enabled": True,
        "required_for_backtest": False,
        "priority": "P0",
        "account_boundary": "普通股票账户可用",
        "sync_frequency": "盘中 3-5 秒、盘后补齐",
        "notes": "普通查询通常只返回当日成交，必须每日落库。",
    },
    {
        "data_type": "daily_kline",
        "name": "日 K 数据",
        "category": "行情数据",
        "source_module": "xtdata",
        "official_interface": "download_history_data2/download_history_data + get_market_data",
        "local_table": "daily_kline",
        "enabled": True,
        "required_for_backtest": True,
        "priority": "P0",
        "account_boundary": "Level1 行情，普通账户可用",
        "sync_frequency": "盘后、夜间、2026 补齐",
        "notes": "2026 全市场必须可补齐；本地默认保存不复权数据。",
    },
    {
        "data_type": "minute_kline",
        "name": "1 分钟 K 数据",
        "category": "行情数据",
        "source_module": "xtdata",
        "official_interface": "download_history_data2/download_history_data + get_market_data",
        "local_table": "minute_kline",
        "enabled": True,
        "required_for_backtest": True,
        "priority": "P0",
        "account_boundary": "Level1 行情，普通账户可用",
        "sync_frequency": "盘中每分钟延迟补齐、夜间补缺口",
        "notes": "默认只补持仓/策略池/手动股票；全市场分钟 K 必须手动长任务。",
    },
    {
        "data_type": "instrument_detail",
        "name": "合约基础信息",
        "category": "基础资料",
        "source_module": "xtdata",
        "official_interface": "get_instrument_detail(symbol, iscomplete=True)",
        "local_table": "instrument_detail",
        "enabled": True,
        "required_for_backtest": True,
        "priority": "P0",
        "account_boundary": "普通股票账户可用",
        "sync_frequency": "盘前、盘后",
        "notes": "保存前收、涨跌停、可交易状态和官方原始 JSON，用于同步和回测门禁。",
    },
    {
        "data_type": "trading_calendar",
        "name": "交易日历",
        "category": "基础资料",
        "source_module": "xtdata",
        "official_interface": "get_trading_calendar / get_trading_dates",
        "local_table": "trading_calendar",
        "enabled": True,
        "required_for_backtest": True,
        "priority": "P0",
        "account_boundary": "普通股票账户可用",
        "sync_frequency": "盘前、2026 补齐",
        "notes": "优先使用 QMT 官方交易日历；测试隔离数据用工作日演示，不代表真实节假日。",
    },
    {
        "data_type": "financial_indicator",
        "name": "财务主要指标",
        "category": "财务数据",
        "source_module": "xtdata",
        "official_interface": "download_financial_data2 + get_financial_data(Pershareindex)",
        "local_table": "financial_indicator",
        "enabled": False,
        "required_for_backtest": False,
        "priority": "P2",
        "account_boundary": "普通股票账户可用，低频同步",
        "sync_frequency": "夜间、周末",
        "notes": "回测使用必须按披露日期控制，避免未来函数。",
    },
]
