import type { editor } from 'monaco-editor/esm/vs/editor/editor.api.js';

export const localQuantCodeEditorThemes: Record<'lqc-ibkr-dark' | 'lqc-ibkr-light', editor.IStandaloneThemeData> = {
  'lqc-ibkr-dark': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'd8dee9', background: '080b10' },
      { token: 'comment', foreground: '6f7c8f', fontStyle: 'italic' },
      { token: 'keyword', foreground: '7db7ff' },
      { token: 'string', foreground: '9fe6b8' },
      { token: 'number', foreground: 'facc15' },
      { token: 'type', foreground: 'c084fc' },
      { token: 'function', foreground: '60a5fa' },
    ],
    colors: {
      'editor.background': '#080b10',
      'editor.foreground': '#d8dee9',
      'editor.lineHighlightBackground': '#111720',
      'editorLineNumber.foreground': '#526172',
      'editorLineNumber.activeForeground': '#d8dee9',
      'editorGutter.background': '#080b10',
      'editor.selectionBackground': '#1e3a5f',
      'editor.inactiveSelectionBackground': '#182235',
      'editorCursor.foreground': '#58a6ff',
      'editorIndentGuide.background1': '#202530',
      'editorIndentGuide.activeBackground1': '#303746',
      'editorWidget.background': '#11141d',
      'editorWidget.border': '#303746',
      'input.background': '#11131b',
      'input.border': '#303746',
      'dropdown.background': '#11131b',
      'dropdown.border': '#303746',
      'list.hoverBackground': '#151c2a',
      'list.activeSelectionBackground': '#111c33',
    },
  },
  'lqc-ibkr-light': {
    base: 'vs',
    inherit: true,
    rules: [
      { token: '', foreground: '172033', background: 'ffffff' },
      { token: 'comment', foreground: '6b7280', fontStyle: 'italic' },
      { token: 'keyword', foreground: '1559d8' },
      { token: 'string', foreground: '047857' },
      { token: 'number', foreground: 'b45309' },
      { token: 'type', foreground: '6d28d9' },
      { token: 'function', foreground: '0b77df' },
    ],
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#172033',
      'editor.lineHighlightBackground': '#eef5ff',
      'editorLineNumber.foreground': '#94a3b8',
      'editorLineNumber.activeForeground': '#172033',
      'editorGutter.background': '#ffffff',
      'editor.selectionBackground': '#bfdbfe',
      'editor.inactiveSelectionBackground': '#e6edf5',
      'editorCursor.foreground': '#0b77df',
      'editorIndentGuide.background1': '#d9e2ee',
      'editorIndentGuide.activeBackground1': '#94a3b8',
      'editorWidget.background': '#ffffff',
      'editorWidget.border': '#c8d3e1',
      'input.background': '#ffffff',
      'input.border': '#c8d3e1',
      'dropdown.background': '#ffffff',
      'dropdown.border': '#c8d3e1',
      'list.hoverBackground': '#eef5ff',
      'list.activeSelectionBackground': '#dbeafe',
    },
  },
};
